config/routes.rb
Rails.application.routes.draw do
  resources :ui_libraries do
    scope module: :ui_libraries do
      resource :preferences, only: [:show, :create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "ui_libraries#index"
end

app/models/ui_library.rb
class UiLibrary < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates_presence_of :name
  validates_uniqueness_of :name

  after_update_commit :update_preview_elements

  private

    def update_preview_elements
      broadcast_replace_to(self, :preferences, target: "preview-element", partial: "ui_libraries/preferences/preview_element",
        locals: { ui_library: self })
      broadcast_replace_to(self, target: "button-section", partial: "ui_libraries/button_section",
        locals: { ui_library: self })
    end
end

app/controllers/ui_libraries/preferences_controller.rb
module UiLibraries
  class PreferencesController < ApplicationController
    before_action :set_ui_library
    def show; end;

    def create
      # Handle post request from page to update preferences on model
      @ui_library.update(preference_params)
      redirect_to ui_library_preferences_path(@ui_library)
    end
  private
    def preference_params
      params.expect(ui_library: [:edge_style_preference, :background_color_preference, :text_color_preference, :background_color_level, :text_color_level])
    end

    def set_ui_library
      @ui_library = UiLibrary.friendly.find(params[:ui_library_id])
    end
  end
end

app/controllers/ui_libraries_controller.rb
class UiLibrariesController < ApplicationController
  before_action :set_ui_library, only: %i[ show edit update destroy ]

  # GET /ui_libraries or /ui_libraries.json
  def index
    @ui_libraries = UiLibrary.all
  end

  # GET /ui_libraries/1 or /ui_libraries/1.json
  def show
  end

  # GET /ui_libraries/new
  def new
    @ui_library = UiLibrary.new
  end

  # GET /ui_libraries/1/edit
  def edit
  end

  # POST /ui_libraries or /ui_libraries.json
  def create
    @ui_library = UiLibrary.new(ui_library_params)

    respond_to do |format|
      if @ui_library.save
        format.html { redirect_to @ui_library, notice: "Ui library was successfully created." }
        format.json { render :show, status: :created, location: @ui_library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ui_library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ui_libraries/1 or /ui_libraries/1.json
  def update
    respond_to do |format|
      if @ui_library.update(ui_library_params)
        format.html { redirect_to @ui_library, notice: "Ui library was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @ui_library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ui_library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ui_libraries/1 or /ui_libraries/1.json
  def destroy
    @ui_library.destroy!

    respond_to do |format|
      format.html { redirect_to ui_libraries_path, notice: "Ui library was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ui_library
      @ui_library = UiLibrary.friendly.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def ui_library_params
      params.expect(ui_library: [ :name ])
    end
end

app/helpers/ui_libraries_helper.rb
module UiLibrariesHelper
  def button_roundedness_for_preference(edge_style_preference)
    case edge_style_preference
    when "rounded"
      "rounded-full"
    when "slightly_rounded"
      "rounded-lg"
    when "square"
      ""
    else
      ""
    end
  end

  def background_color_preference(preference, level = 5)
    case level
    when 0
      case preference
      when "red"
        'bg-red-50'
      when "orange"
        'bg-orange-50'
      when "amber"
        'bg-amber-50'
      when "yellow"
        'bg-yellow-50'
      when "lime"
        'bg-lime-50'
      when "green"
        'bg-green-50'
      when "emerald"
        'bg-emerald-50'
      when "teal"
        'bg-teal-50'
      when "cyan"
        'bg-cyan-50'
      when "sky"
        'bg-sky-50'
      when "blue"
        'bg-blue-50'
      when "indigo"
        'bg-indigo-50'
      when "violet"
        'bg-violet-50'
      when "purple"
        'bg-purple-50'
      when "fuchsia"
        'bg-fuchsia-50'
      when "pink"
        'bg-pink-50'
      when "rose"
        'bg-rose-50'
      when "slate"
        'bg-slate-50'
      when "gray"
        'bg-gray-50'
      when "zinc"
        'bg-zinc-50'
      when "neutral"
        'bg-neutral-50'
      when "stone"
        'bg-stone-50'
      end
    when 1
      case preference
      when "red"
        'bg-red-100'
      when "orange"
        'bg-orange-100'
      when "amber"
        'bg-amber-100'
      when "yellow"
        'bg-yellow-100'
      when "lime"
        'bg-lime-100'
      when "green"
        'bg-green-100'
      when "emerald"
        'bg-emerald-100'
      when "teal"
        'bg-teal-100'
      when "cyan"
        'bg-cyan-100'
      when "sky"
        'bg-sky-100'
      when "blue"
        'bg-blue-100'
      when "indigo"
        'bg-indigo-100'
      when "violet"
        'bg-violet-100'
      when "purple"
        'bg-purple-100'
      when "fuchsia"
        'bg-fuchsia-100'
      when "pink"
        'bg-pink-100'
      when "rose"
        'bg-rose-100'
      when "slate"
        'bg-slate-100'
      when "gray"
        'bg-gray-100'
      when "zinc"
        'bg-zinc-100'
      when "neutral"
        'bg-neutral-100'
      when "stone"
        'bg-stone-100'
      end
    when 2
      case preference
      when "red"
        'bg-red-200'
      when "orange"
        'bg-orange-200'
      when "amber"
        'bg-amber-200'
      when "yellow"
        'bg-yellow-200'
      when "lime"
        'bg-lime-200'
      when "green"
        'bg-green-200'
      when "emerald"
        'bg-emerald-200'
      when "teal"
        'bg-teal-200'
      when "cyan"
        'bg-cyan-200'
      when "sky"
        'bg-sky-200'
      when "blue"
        'bg-blue-200'
      when "indigo"
        'bg-indigo-200'
      when "violet"
        'bg-violet-200'
      when "purple"
        'bg-purple-200'
      when "fuchsia"
        'bg-fuchsia-200'
      when "pink"
        'bg-pink-200'
      when "rose"
        'bg-rose-200'
      when "slate"
        'bg-slate-200'
      when "gray"
        'bg-gray-200'
      when "zinc"
        'bg-zinc-200'
      when "neutral"
        'bg-neutral-200'
      when "stone"
        'bg-stone-200'
      end
    when 3
      case preference
      when "red"
        'bg-red-300'
      when "orange"
        'bg-orange-300'
      when "amber"
        'bg-amber-300'
      when "yellow"
        'bg-yellow-300'
      when "lime"
        'bg-lime-300'
      when "green"
        'bg-green-300'
      when "emerald"
        'bg-emerald-300'
      when "teal"
        'bg-teal-300'
      when "cyan"
        'bg-cyan-300'
      when "sky"
        'bg-sky-300'
      when "blue"
        'bg-blue-300'
      when "indigo"
        'bg-indigo-300'
      when "violet"
        'bg-violet-300'
      when "purple"
        'bg-purple-300'
      when "fuchsia"
        'bg-fuchsia-300'
      when "pink"
        'bg-pink-300'
      when "rose"
        'bg-rose-300'
      when "slate"
        'bg-slate-300'
      when "gray"
        'bg-gray-300'
      when "zinc"
        'bg-zinc-300'
      when "neutral"
        'bg-neutral-300'
      when "stone"
        'bg-stone-300'
      end
    when 4
      case preference
      when "red"
        'bg-red-400'
      when "orange"
        'bg-orange-400'
      when "amber"
        'bg-amber-400'
      when "yellow"
        'bg-yellow-400'
      when "lime"
        'bg-lime-400'
      when "green"
        'bg-green-400'
      when "emerald"
        'bg-emerald-400'
      when "teal"
        'bg-teal-400'
      when "cyan"
        'bg-cyan-400'
      when "sky"
        'bg-sky-400'
      when "blue"
        'bg-blue-400'
      when "indigo"
        'bg-indigo-400'
      when "violet"
        'bg-violet-400'
      when "purple"
        'bg-purple-400'
      when "fuchsia"
        'bg-fuchsia-400'
      when "pink"
        'bg-pink-400'
      when "rose"
        'bg-rose-400'
      when "slate"
        'bg-slate-400'
      when "gray"
        'bg-gray-400'
      when "zinc"
        'bg-zinc-400'
      when "neutral"
        'bg-neutral-400'
      when "stone"
        'bg-stone-400'
      end
    when 5
      case preference
      when "red"
        'bg-red-500'
      when "orange"
        'bg-orange-500'
      when "amber"
        'bg-amber-500'
      when "yellow"
        'bg-yellow-500'
      when "lime"
        'bg-lime-500'
      when "green"
        'bg-green-500'
      when "emerald"
        'bg-emerald-500'
      when "teal"
        'bg-teal-500'
      when "cyan"
        'bg-cyan-500'
      when "sky"
        'bg-sky-500'
      when "blue"
        'bg-blue-500'
      when "indigo"
        'bg-indigo-500'
      when "violet"
        'bg-violet-500'
      when "purple"
        'bg-purple-500'
      when "fuchsia"
        'bg-fuchsia-500'
      when "pink"
        'bg-pink-500'
      when "rose"
        'bg-rose-500'
      when "slate"
        'bg-slate-500'
      when "gray"
        'bg-gray-500'
      when "zinc"
        'bg-zinc-500'
      when "neutral"
        'bg-neutral-500'
      when "stone"
        'bg-stone-500'
      end
    when 6
      case preference
      when "red"
        'bg-red-600'
      when "orange"
        'bg-orange-600'
      when "amber"
        'bg-amber-600'
      when "yellow"
        'bg-yellow-600'
      when "lime"
        'bg-lime-600'
      when "green"
        'bg-green-600'
      when "emerald"
        'bg-emerald-600'
      when "teal"
        'bg-teal-600'
      when "cyan"
        'bg-cyan-600'
      when "sky"
        'bg-sky-600'
      when "blue"
        'bg-blue-600'
      when "indigo"
        'bg-indigo-600'
      when "violet"
        'bg-violet-600'
      when "purple"
        'bg-purple-600'
      when "fuchsia"
        'bg-fuchsia-600'
      when "pink"
        'bg-pink-600'
      when "rose"
        'bg-rose-600'
      when "slate"
        'bg-slate-600'
      when "gray"
        'bg-gray-600'
      when "zinc"
        'bg-zinc-600'
      when "neutral"
        'bg-neutral-600'
      when "stone"
        'bg-stone-600'
      end
    when 7
      case preference
      when "red"
        'bg-red-700'
      when "orange"
        'bg-orange-700'
      when "amber"
        'bg-amber-700'
      when "yellow"
        'bg-yellow-700'
      when "lime"
        'bg-lime-700'
      when "green"
        'bg-green-700'
      when "emerald"
        'bg-emerald-700'
      when "teal"
        'bg-teal-700'
      when "cyan"
        'bg-cyan-700'
      when "sky"
        'bg-sky-700'
      when "blue"
        'bg-blue-700'
      when "indigo"
        'bg-indigo-700'
      when "violet"
        'bg-violet-700'
      when "purple"
        'bg-purple-700'
      when "fuchsia"
        'bg-fuchsia-700'
      when "pink"
        'bg-pink-700'
      when "rose"
        'bg-rose-700'
      when "slate"
        'bg-slate-700'
      when "gray"
        'bg-gray-700'
      when "zinc"
        'bg-zinc-700'
      when "neutral"
        'bg-neutral-700'
      when "stone"
        'bg-stone-700'
      end
    when 8
      case preference
      when "red"
        'bg-red-800'
      when "orange"
        'bg-orange-800'
      when "amber"
        'bg-amber-800'
      when "yellow"
        'bg-yellow-800'
      when "lime"
        'bg-lime-800'
      when "green"
        'bg-green-800'
      when "emerald"
        'bg-emerald-800'
      when "teal"
        'bg-teal-800'
      when "cyan"
        'bg-cyan-800'
      when "sky"
        'bg-sky-800'
      when "blue"
        'bg-blue-800'
      when "indigo"
        'bg-indigo-800'
      when "violet"
        'bg-violet-800'
      when "purple"
        'bg-purple-800'
      when "fuchsia"
        'bg-fuchsia-800'
      when "pink"
        'bg-pink-800'
      when "rose"
        'bg-rose-800'
      when "slate"
        'bg-slate-800'
      when "gray"
        'bg-gray-800'
      when "zinc"
        'bg-zinc-800'
      when "neutral"
        'bg-neutral-800'
      when "stone"
        'bg-stone-800'
      end
    when 9
      case preference
      when "red"
        'bg-red-900'
      when "orange"
        'bg-orange-900'
      when "amber"
        'bg-amber-900'
      when "yellow"
        'bg-yellow-900'
      when "lime"
        'bg-lime-900'
      when "green"
        'bg-green-900'
      when "emerald"
        'bg-emerald-900'
      when "teal"
        'bg-teal-900'
      when "cyan"
        'bg-cyan-900'
      when "sky"
        'bg-sky-900'
      when "blue"
        'bg-blue-900'
      when "indigo"
        'bg-indigo-900'
      when "violet"
        'bg-violet-900'
      when "purple"
        'bg-purple-900'
      when "fuchsia"
        'bg-fuchsia-900'
      when "pink"
        'bg-pink-900'
      when "rose"
        'bg-rose-900'
      when "slate"
        'bg-slate-900'
      when "gray"
        'bg-gray-900'
      when "zinc"
        'bg-zinc-900'
      when "neutral"
        'bg-neutral-900'
      when "stone"
        'bg-stone-900'
      end
    end
  end

app/views/ui_libraries/_button_section.html.erb
<div class="mt-8 min-h-[60vh]" id="button-section">
  <h3 class="font-semibold text-2xl"> Button Section </h3>
  <p class="text-lg"> Your custom button UI elements </p>
  
  <div class="flex mt-8 rounded-t border border-gray-900">
    <%= link_to ui_library_path(ui_library, tab: :preview), class: "p-2 #{"bg-gray-300" if params[:tab].in?([nil, "preview"])}" do %>
      <span> Preview </span>
    <% end %>
    <%= link_to ui_library_path(ui_library, tab: :html), class: "p-2 #{"bg-gray-300" if params[:tab] == "html" }" do %>
      <span> HTML </span>
    <% end %>
  </div>
  <div class="max-h-80 w-full border border-gray-900 border-t-0 rounded-b bg-gray-200 p-4">
    <% if params[:tab].nil? || params[:tab] == "preview" %>
      <div class="flex gap-8">
        <%= render Buttons::PrimaryComponent.new(ui_library) %>
      </div>
    <% end %>

    <% if params[:tab] == "html" %>
      <textarea readonly class="w-full focus:border-0 focus:ring-0 focus:outline-none">
<%= render Buttons::PrimaryComponent.new(ui_library) %></textarea>
    <% end %>
  </div>
</div>

app/views/ui_libraries/_form.html.erb
<%= form_with(model: ui_library, class: "contents") do |form| %>
  <% if ui_library.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(ui_library.errors.count, "error") %> prohibited this ui_library from being saved:</h2>

      <ul class="list-disc ml-6">
        <% ui_library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": ui_library.errors[:name].none?, "border-red-400 focus:outline-red-600": ui_library.errors[:name].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/ui_libraries/_preview_element.html.erb
<div class="max-w-md w-full flex-shrink-0" id="preview-element">
  <div class="w-full h-64 flex justify-center items-center <%= button_roundedness_for_preference(ui_library.edge_style_preference) %> <%= background_color_preference(ui_library.background_color_preference, ui_library.background_color_level) %>"> 
    <span class="text-3xl font-semibold <%= text_color_preference(ui_library.text_color_preference, ui_library.text_color_level) %>"> 
      <%= ui_library.name %> UI
    </span>
  </div>
</div>

app/views/ui_libraries/_ui_library.html.erb
<div id="<%= dom_id ui_library %>" class="w-full h-40 bg-white rounded-lg shadow-lg p-4 flex flex-col justify-between">
  <%= link_to ui_library do %>
    <span class="text-2xl font-semibold">
      <%= ui_library.name %> UI
    </span>
  <% end %>
  <div class="flex items-center gap-2">
    <%= link_to "Show", ui_library, class: "" %>
    <%= link_to "Edit", edit_ui_library_path(ui_library), class: "" %>
    <%= button_to "Destroy", ui_library, method: :delete, class: "", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>

app/views/ui_libraries/edit.html.erb
<% content_for :title, "Editing ui library" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ui library</h1>

  <%= render "form", ui_library: @ui_library %>

  <%= link_to "Show this ui library", @ui_library, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to ui libraries", ui_libraries_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/ui_libraries/index.html.erb
<% content_for :title, "Your UI libraries" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% if @ui_libraries.any? %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Your UI Libraries</h1>
    </div>

    <div id="ui_libraries" class="w-full grid lg:grid-cols-4 gap-8 mt-8">
        <% @ui_libraries.each do |ui_library| %>
          <%= render ui_library %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2 hidden">
            <%= link_to "Show", ui_library, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_ui_library_path(ui_library), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", ui_library, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        <% end %>
    </div>
  <% else %>
    <h1 class="font-bold text-4xl text-center">You haven't created any UI libraries yet.</h1>
    <p class="text-center my-10"> </p>
    <%= link_to "Create one now", new_ui_library_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white w-40 flex items-center justify-center mx-auto font-medium" %>
  <% end %>
</div>

app/views/ui_libraries/new.html.erb
<% content_for :title, "New ui library" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ui library</h1>

  <%= render "form", ui_library: @ui_library %>

  <%= link_to "Back to ui libraries", ui_libraries_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/ui_libraries/show.html.erb
<% content_for :title, "#{@ui_library.name} UI" %>
<%= turbo_stream_from @ui_library %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl mb-4"><%= @ui_library.name %> UI </h1>
  <%= link_to "Customization settings", ui_library_preferences_path(@ui_library), class: "text-lg" %>

  <%= turbo_frame_tag :button_section do %>
    <%= render "button_section", ui_library: @ui_library %>
  <% end %>
  
  <div class="flex gap-4 mt-8">
    <%= link_to "Edit this ui library", edit_ui_library_path(@ui_library), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "Back to ui libraries", ui_libraries_path, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= button_to "Destroy this ui library", @ui_library, method: :delete, form_class: "sm:inline-block", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>